name: okane
version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    user: node
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    user: node
    ports:
      - "3000:3000"
    environment:
      - MONGO_USERNAME=moneybooks
      - MONGO_PASSWORD=moneybooks
      - MONGO_RESOURCE=mongodb:27017/moneybooks
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongodb
    volumes:
      - ../backend:/app
      - backend_node_modules:/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=moneybooks
      - MONGO_INITDB_ROOT_PASSWORD=moneybooks
      - MONGO_INITDB_DATABASE=moneybooks
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules:
